### ISSUE TITLE
Peer-to-peer code review April 20th

### ISSUE THREAD

**Issue by oovillagran** [Javed-Shahbaz/LeadBoard#2]
Hi, @Javed-Shahbaz !!!

Your project looks good so far. Now, you have to continue with the second milestone of the project. Please take into account the following recommendations:

- Send and receive data from an API - You can use [postman](https://www.postman.com/) services to reach this requirement.
- Use arrow functions instead of the function keyword.
- Use async and await JavaScript features to consume the API.
- Please read carefully the working whit API's and JSON lessons. Because we need to follow this instructions to complete this part of the exercise.

![CarlDelindenForestofwiresGIF](https://user-images.githubusercontent.com/122847613/233396688-e13992ea-5591-4def-a367-511667827c21.gif)

**Comment by Javed-Shahbaz** [comment]
completed
